spring:
  application:
    name: payment-api
  datasource:
    url: ${PAYMENT_DB_URL}
    username: ${PAYMENT_DB_USERNAME}
    password: ${PAYMENT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    enabled: true

user_api:
    url: ${USER_API_URL}
    get-user: /dummy-auth/get-user